markdown: kramdown
highlighter: rouge
permalink: /blog/:title
title: Divina Proportione
date: Jun 7-9
year: 2017
tickets: true
tickets-eb: //eventbrite.com/tickets-external?eid=28863864596&ref=etckt
tickets-eb-link: http://kerning-2017.eventbrite.com
speakers: false
workshops: true
schedule: false
cfs: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
kramdown:
  input: GFM
